[phases.setup]
nixPkgs = ["...", "gcc", "gnumake", "pkg-config"]
aptPkgs = ["...", "build-essential", "python3"]

[phases.build]
cmds = ["npm rebuild better-sqlite3 --build-from-source"]

[start]
cmd = "node server.js"
